import { test, expect } from '@playwright/test';

const baseUrl = process.env.METADELTA_BASE_URL ?? baseUrl;

test('test', async ({ page }) => {
  await page.goto('https://ruby-customer-2903--pocdev02.sandbox.lightning.force.com/lightning/o/UserAppMenuItem/home');
  await page.getByRole('button', { name: 'Setup' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('menuitem', { name: 'Setup Opens in a new tab Setup for current app' }).click();
  const page1 = await page1Promise;
  await page1.getByRole('searchbox', { name: 'Quick Find' }).click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).fill('Einstein Setup');
  await page1.getByRole('link', { name: 'Einstein Setup' }).click();
  await page1.locator('.slds-checkbox_faux').first().click();
  await page1.waitForTimeout(20000);
  await page1.keyboard.press('Control+R');
  await page1.close();
  await page.getByRole('button', { name: 'Setup' }).click();
  const page1Promise = page.waitForEvent('popup');
  //await page1.goto('https://ruby-customer-2903--pocdev02.sandbox.my.salesforce-setup.com/lightning/setup/EinsteinGPTSetup/home');
  await page1.getByRole('searchbox', { name: 'Quick Find' }).click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).fill('Agentforce Agents');
  await page1.getByRole('link', { name: 'Agentforce Agents' }).click();
  await page1.locator('.slds-checkbox_faux').click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).fill('Users');
  await page1.getByRole('link', { name: 'Users' }).nth(1).click();
  await page1.locator('iframe[name="vfFrameId_1772137752963"]').contentFrame().getByRole('link', { name: 'Villalobos, Nerio' }).nth(2).click();
  await page1.locator('iframe[name="vfFrameId_1772137819218"]').contentFrame().getByRole('link', { name: 'Permission Set Assignments[0]' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137819218"]').contentFrame().getByRole('row', { name: 'Permission Set Assignments Edit Assignments Permission Set Assignments Help' }).locator('input[name="editPermSetAssignments"]').click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByLabel('Available Permission Sets').selectOption('0PSfn000001KgOI');
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByRole('link', { name: 'Add' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByLabel('Available Permission Sets').selectOption('0PSfn000001HrA0');
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByRole('link', { name: 'Add' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByLabel('Available Permission Sets').selectOption('0PSfn000001Ht5z');
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByRole('link', { name: 'Add' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByLabel('Available Permission Sets').selectOption('0PSfn000001Kiac');
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByRole('link', { name: 'Add' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByLabel('Available Permission Sets').selectOption('0PSfn000001Hr9y');
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().getByRole('link', { name: 'Add' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137839299"]').contentFrame().locator('input[name="thePage:theForm:thePageBlock:j_id22:save"]').click();
  await page1.locator('iframe[name="vfFrameId_1772137925259"]').contentFrame().getByRole('link', { name: 'Permission Set Assignments[5]' }).click();
  await page1.locator('iframe[name="vfFrameId_1772137925259"]').contentFrame().getByRole('row', { name: 'Permission Set Assignments Edit Assignments Permission Set Assignments Help' }).locator('input[name="editPermSetAssignments"]').click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).fill('Agentforce Agents');
  await page1.getByRole('link', { name: 'Agentforce Agents' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('button', { name: 'New Agent' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('heading', { name: 'Agentforce Employee Agent' }).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('textbox', { name: 'Name', exact: true }).click();
  await page2.getByRole('textbox', { name: 'Name', exact: true }).fill('Agentforce Employee Puntos');
  await page2.getByRole('textbox', { name: 'API Name' }).click();
  await page2.getByRole('textbox', { name: 'API Name' }).fill('Agentforce_Employee_Puntos ');
  await page2.getByPlaceholder('Example: Work leads by').click();
  await page2.getByPlaceholder('Example: Work leads by').fill('Automates common business tasks and assists employees in their flow of work. The agent answers user inquiries by searching authorized Knowledge articles and connected data sources, providing accurate and contextual responses. It can also execute automations and actions to improve productivity and operational efficiency');
  await page2.getByPlaceholder('Example: You\'re a Digital').click();
  await page2.getByPlaceholder('Example: You\'re a Digital').fill('You are an Agentforce Employee Agent');
  await page2.getByPlaceholder('Example: Your company').click();
  await page2.getByPlaceholder('Example: Your company').fill('Your company specializes in customer loyalty and rewards programs, enabling users to earn and redeem points across a network of partner brands in Colombia. ');
  await page2.locator('.slds-checkbox_faux').click();
  await page2.getByRole('button', { name: 'Next' }).click();
  await page2.getByRole('button', { name: 'Create' }).click();
  await page1.bringToFront();
  await page1.waitForLoadState('domcontentloaded');
  await page1.getByRole('searchbox', { name: 'Quick Find' }).click();
  await page1.getByRole('searchbox', { name: 'Quick Find' }).fill('Trusted URLs');
  await page1.getByRole('link', { name: 'Trusted URLs', exact: true }).click();
  await page1.locator('iframe[name="vfFrameId_1772198118660"]').contentFrame().getByRole('button', { name: 'New Trusted URL' }).click();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('textbox', { name: '* API Name' }).click();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('textbox', { name: '* API Name' }).fill('Puntos_Colombia_Empresas_Page');
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('textbox', { name: '* URL' }).click();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('textbox', { name: '* URL' }).fill('https://www.puntoscolombia.com');
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('checkbox', { name: 'connect-src (scripts)' }).check();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('checkbox', { name: 'font-src (fonts)' }).check();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('checkbox', { name: 'frame-src (iframe content)' }).check();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('checkbox', { name: 'style-src (stylesheets)' }).check();
  await page1.locator('iframe[name="vfFrameId_1772198124506"]').contentFrame().getByRole('row', { name: 'Save Save & New Cancel', exact: true }).locator('input[name="save"]').click();
});